- name: Configure apache2/httpd based on OS flavour
  hosts: all
  become: yes
  tasks:

    - name: Install apache2 on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install httpd on RedHat
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Edit the index.html file
      copy:
        content: "IntelliQ"
        dest: /var/www/html/index.html

    - name: Restart apache2 on Ubuntu
      service:
        name: apache2
        state: restarted
      when: ansible_facts['os_family'] == "Debian"

    - name: Restart httpd on RedHat
      service:
        name: httpd
        state: restarted
      when: ansible_facts['os_family'] == "RedHat"

    - name: Check apache2/httpd response on all servers
      uri:
        url: "{{ item }}"
        status_code: 200
      loop:
        - http://172.31.93.74
        - http://172.31.83.244
        - http://172.31.92.116
...
