---
- name: install docker on all servers
  hosts: all
  tasks:
    - name: download the docker shell script
      shell: curl -fsSL https://get.docker.com -o install-docker.sh
    - name: execute the docker shell script
      shell: sudo sh install-docker.sh
...

