---
- name: Install tree on ubuntu servers
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update apt cache and install tree
      apt:
        name: tree
        state: present
        update_cache: yes

- name: Install tree on redhat servers
  hosts: redhat
  become: yes
  tasks:
    - name: Install tree using yum
      yum:
        name: tree
        state: present
...

