---
- name: Implementing handlers
  hosts: all
  become: true

  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: Restart apache2
    - name: Edit the index.html file
      copy:
        content: "IntelliQ"
        dest: /var/www/html/index.html
      notify: Restart apache2

  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
    - name: Check apache response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.92.116
        - http://172.31.83.244   
...
