---
- name: Capture OS info
  hosts: all
  tasks:
    - name: Capture OS name
      debug:
        var: "{{ansible_distribution}}u"
    - name: Capture OS version
      debug:
        var: "{{ansible_distribution_version}}"
    - name: Capture 0S major version info
      debug:
        var: "{{ansible_distribution_major_version}}" 
